# Generated by Django 4.1.1 on 2022-09-16 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pontoturisticomodel_aprovado'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PontoTuristicoModel',
            new_name='PontoTuristico',
        ),
    ]
