# Generated by Django 4.1.1 on 2022-09-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enderecos', '0001_initial'),
        ('core', '0006_pontoturistico_avaliacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontoturistico',
            name='enderecos',
            field=models.ManyToManyField(to='enderecos.endereco'),
        ),
    ]
