# Generated by Django 4.1.1 on 2022-09-16 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AtracaoModel',
            new_name='Atracao',
        ),
    ]
